apiVersion: v1
kind: Service
metadata:
  name: volunteer-service
  namespace: volunteer-namespace
  labels:
    app: volunteer-service
    app.kubernetes.io/part-of: solidarytech
spec:
  type: ClusterIP
  selector: { app: volunteer-service }
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: metrics
      port: 9464
      targetPort: 9464
