apiVersion: v1
kind: Service
metadata:
  name: ngo-service
  namespace: ngo-namespace
  labels:
    app: ngo-service
    app.kubernetes.io/part-of: solidarytech
spec:
  type: ClusterIP
  selector: { app: ngo-service }
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: metrics
      port: 9464
      targetPort: 9464
